/*
 green-turtle version 1.4.0 Copyright (c) 2011-2013, R. Alexander Milowski <alex@milowski.com> All rights reserved. */
function URIResolver(){}URIResolver.SCHEME=/^[A-Za-z][A-Za-z0-9\+\-\.]*\:/;
URIResolver.prototype.parseURI=function(a){var b=URIResolver.SCHEME.exec(a);if(!b)throw"Bad URI value, no scheme: "+a;a={spec:a};a.scheme=b[0].substring(0,b[0].length-1);a.schemeSpecificPart=a.spec.substring(b[0].length);"/"==a.schemeSpecificPart.charAt(0)&&"/"==a.schemeSpecificPart.charAt(1)?this.parseGeneric(a):a.isGeneric=!1;a.normalize=function(){if(this.isGeneric&&0!=this.segments.length){if(1<this.path.length&&"/."==this.path.substring(this.path.length-2))this.path=this.path.substring(0,this.path.length-
1),this.segments.splice(this.segments.length-1,1);else{var a=this.path.charAt(this.path.length-1);"/"!=a&&(a="");for(var b=0;b<this.segments.length;b++)0<b&&".."==this.segments[b]&&(this.segments.splice(b-1,2),b-=2),"."==this.segments[b]&&(this.segments.splice(b,1),b--);this.path=0==this.segments.length?"/":"/"+this.segments.join("/")+a}this.schemeSpecificPart="//"+this.authority+this.path;"undefined"!=typeof this.query&&(this.schemeSpecificPart+="?"+this.query);"undefined"!=typeof this.fragment&&
(this.schemeSpecificPart+="#"+this.fragment);this.spec=this.scheme+":"+this.schemeSpecificPart}};a.resolve=function(a){if(!a)return this.spec;if("#"==a.charAt(0)){var b=this.spec.lastIndexOf("#");return 0>b?this.spec+a:this.spec.substring(0,b)+a}if(!this.isGeneric)throw"Cannot resolve uri against non-generic URI: "+this.spec;a.indexOf(":");if("/"==a.charAt(0))return this.scheme+"://"+this.authority+a;if("."==a.charAt(0)&&"/"==a.charAt(1)){if("/"==this.path.charAt(this.path.length-1))return this.scheme+
"://"+this.authority+this.path+a.substring(2);b=this.path.lastIndexOf("/");return this.scheme+"://"+this.authority+this.path.substring(0,b)+a.substring(1)}if(URIResolver.SCHEME.test(a))return a;if("?"==a.charAt(0)||"/"==this.path.charAt(this.path.length-1))return this.scheme+"://"+this.authority+this.path+a;b=this.path.lastIndexOf("/");return this.scheme+"://"+this.authority+this.path.substring(0,b+1)+a};a.relativeTo=function(a){if(a.scheme!=this.scheme)return this.spec;if(!this.isGeneric)throw"A non generic URI cannot be made relative: "+
this.spec;if(!a.isGeneric)throw"Cannot make a relative URI against a non-generic URI: "+a.spec;if(a.authority!=this.authority)return this.spec;for(var b=0;b<this.segments.length&&b<a.segments.length;b++)if(this.segments[b]!=a.segments[b]){for(var d="/"==a.path.charAt(a.path.length-1)?0:-1,h="",l=b;l<a.segments.length+d;l++)h+="../";for(l=b;l<this.segments.length;l++)h+=this.segments[l],l+1<this.segments.length&&(h+="/");"/"==this.path.charAt(this.path.length-1)&&(h+="/");return h}if(this.segments.length==
a.segments.length)return this.hash?this.hash:this.query?this.query:"";if(b<this.segments.length){h="";for(l=b;l<this.segments.length;l++)h+=this.segments[l],l+1<this.segments.length&&(h+="/");"/"==this.path.charAt(this.path.length-1)&&(h+="/");return h}throw"Cannot calculate a relative URI for "+this.spec+" against "+a.spec;};return a};
URIResolver.prototype.parseGeneric=function(a){if("/"!=a.schemeSpecificPart.charAt(0)||"/"!=a.schemeSpecificPart.charAt(1))throw"Generic URI values should start with '//':"+a.spec;var b=a.schemeSpecificPart.substring(2),c=b.indexOf("/");a.authority=0>c?b:b.substring(0,c);a.path=0>c?"":b.substring(c);b=a.path.indexOf("#");0<=b&&(a.fragment=a.path.substring(b+1),a.path=a.path.substring(0,b));b=a.path.indexOf("?");0<=b&&(a.query=a.path.substring(b+1),a.path=a.path.substring(0,b));if("/"==a.path||""==
a.path)a.segments=[];else for(a.segments=a.path.split(/\//),0<a.segments.length&&""==a.segments[0]&&1<a.path.length&&"/"!=a.path.charAt(1)&&a.segments.shift(),0<a.segments.length&&0<a.path.length&&"/"==a.path.charAt(a.path.length-1)&&""==a.segments[a.segments.length-1]&&1<a.path.length&&"/"!=a.path.charAt(a.path.length-2)&&a.segments.pop(),b=0;b<a.segments.length;b++)for(var c=a.segments[b].split(/%[A-Za-z0-9][A-Za-z0-9]|[\ud800-\udfff][\ud800-\udfff]|[A-Za-z0-9\-\._~!$&'()*+,;=@:\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF]+/),
e=0;e<c.length;e++)if(0<c[e].length)throw"Unecaped character "+c[e].charAt(0)+" ("+c[e].charCodeAt(0)+") in URI "+a.spec;a.isGeneric=!0};RDFaProcessor.prototype=new URIResolver;RDFaProcessor.prototype.constructor=RDFaProcessor;
function RDFaProcessor(a){this.target=a?a:{graph:{subjects:{},prefixes:{},terms:{}}};this.theOne="_:"+(new Date).getTime();this.vocabulary=this.language=null;this.blankCounter=0;this.langAttributes=[{namespaceURI:"http://www.w3.org/XML/1998/namespace",localName:"lang"}];this.inXHTMLMode=!1;this.absURIRE=/[\w\_\-]+:\S+/;this.finishedHandlers=[];this.init()}RDFaProcessor.prototype.newBlankNode=function(){this.blankCounter++;return"_:"+this.blankCounter};RDFaProcessor.XMLLiteralURI="http://www.w3.org/1999/02/22-rdf-syntax-ns#XMLLiteral";
RDFaProcessor.HTMLLiteralURI="http://www.w3.org/1999/02/22-rdf-syntax-ns#HTML";RDFaProcessor.PlainLiteralURI="http://www.w3.org/1999/02/22-rdf-syntax-ns#PlainLiteral";RDFaProcessor.objectURI="http://www.w3.org/1999/02/22-rdf-syntax-ns#object";RDFaProcessor.typeURI="http://www.w3.org/1999/02/22-rdf-syntax-ns#type";RDFaProcessor.nameChar="[-A-Z_a-z\u00c0-\u00d6\u00d8-\u00f6\u00f8-\u02ff\u0370-\u037d\u037f-\u1fff\u200c-\u200d\u2070-\u218f\u2c00-\u2fef\u3001-\ud7ff\uf900-\ufdcf\ufdf0-\ufffd\u10000-\uefffF.0-9\u00b7\u0300-\u036f\u203f-\u2040]";
RDFaProcessor.nameStartChar="[A-Za-z\u00c0-\u00d6\u00d8-\u00f6\u00f8-\u00ff\u0100-\u0131\u0134-\u013e\u0141-\u0148\u014a-\u017e\u0180-\u01c3\u01cd-\u01f0\u01f4-\u01f5\u01fa-\u0217\u0250-\u02a8\u02bb-\u02c1\u0386\u0388-\u038a\u038c\u038e-\u03a1\u03a3-\u03ce\u03d0-\u03d6\u03da\u03dc\u03de\u03e0\u03e2-\u03f3\u0401-\u040c\u040e-\u044f\u0451-\u045c\u045e-\u0481\u0490-\u04c4\u04c7-\u04c8\u04cb-\u04cc\u04d0-\u04eb\u04ee-\u04f5\u04f8-\u04f9\u0531-\u0556\u0559\u0561-\u0586\u05d0-\u05ea\u05f0-\u05f2\u0621-\u063a\u0641-\u064a\u0671-\u06b7\u06ba-\u06be\u06c0-\u06ce\u06d0-\u06d3\u06d5\u06e5-\u06e6\u0905-\u0939\u093d\u0958-\u0961\u0985-\u098c\u098f-\u0990\u0993-\u09a8\u09aa-\u09b0\u09b2\u09b6-\u09b9\u09dc-\u09dd\u09df-\u09e1\u09f0-\u09f1\u0a05-\u0a0a\u0a0f-\u0a10\u0a13-\u0a28\u0a2a-\u0a30\u0a32-\u0a33\u0a35-\u0a36\u0a38-\u0a39\u0a59-\u0a5c\u0a5e\u0a72-\u0a74\u0a85-\u0a8b\u0a8d\u0a8f-\u0a91\u0a93-\u0aa8\u0aaa-\u0ab0\u0ab2-\u0ab3\u0ab5-\u0ab9\u0abd\u0ae0\u0b05-\u0b0c\u0b0f-\u0b10\u0b13-\u0b28\u0b2a-\u0b30\u0b32-\u0b33\u0b36-\u0b39\u0b3d\u0b5c-\u0b5d\u0b5f-\u0b61\u0b85-\u0b8a\u0b8e-\u0b90\u0b92-\u0b95\u0b99-\u0b9a\u0b9c\u0b9e-\u0b9f\u0ba3-\u0ba4\u0ba8-\u0baa\u0bae-\u0bb5\u0bb7-\u0bb9\u0c05-\u0c0c\u0c0e-\u0c10\u0c12-\u0c28\u0c2a-\u0c33\u0c35-\u0c39\u0c60-\u0c61\u0c85-\u0c8c\u0c8e-\u0c90\u0c92-\u0ca8\u0caa-\u0cb3\u0cb5-\u0cb9\u0cde\u0ce0-\u0ce1\u0d05-\u0d0c\u0d0e-\u0d10\u0d12-\u0d28\u0d2a-\u0d39\u0d60-\u0d61\u0e01-\u0e2e\u0e30\u0e32-\u0e33\u0e40-\u0e45\u0e81-\u0e82\u0e84\u0e87-\u0e88\u0e8a\u0e8d\u0e94-\u0e97\u0e99-\u0e9f\u0ea1-\u0ea3\u0ea5\u0ea7\u0eaa-\u0eab\u0ead-\u0eae\u0eb0\u0eb2-\u0eb3\u0ebd\u0ec0-\u0ec4\u0f40-\u0f47\u0f49-\u0f69\u10a0-\u10c5\u10d0-\u10f6\u1100\u1102-\u1103\u1105-\u1107\u1109\u110b-\u110c\u110e-\u1112\u113c\u113e\u1140\u114c\u114e\u1150\u1154-\u1155\u1159\u115f-\u1161\u1163\u1165\u1167\u1169\u116d-\u116e\u1172-\u1173\u1175\u119e\u11a8\u11ab\u11ae-\u11af\u11b7-\u11b8\u11ba\u11bc-\u11c2\u11eb\u11f0\u11f9\u1e00-\u1e9b\u1ea0-\u1ef9\u1f00-\u1f15\u1f18-\u1f1d\u1f20-\u1f45\u1f48-\u1f4d\u1f50-\u1f57\u1f59\u1f5b\u1f5d\u1f5f-\u1f7d\u1f80-\u1fb4\u1fb6-\u1fbc\u1fbe\u1fc2-\u1fc4\u1fc6-\u1fcc\u1fd0-\u1fd3\u1fd6-\u1fdb\u1fe0-\u1fec\u1ff2-\u1ff4\u1ff6-\u1ffc\u2126\u212a-\u212b\u212e\u2180-\u2182\u3041-\u3094\u30a1-\u30fa\u3105-\u312c\uac00-\ud7a3\u4e00-\u9fa5\u3007\u3021-\u3029_]";
RDFaProcessor.NCNAME=new RegExp("^"+RDFaProcessor.nameStartChar+RDFaProcessor.nameChar+"*$");RDFaProcessor.trim=function(a){return a.replace(/^\s\s*/,"").replace(/\s\s*$/,"")};RDFaProcessor.prototype.tokenize=function(a){return RDFaProcessor.trim(a).split(/\s+/)};
RDFaProcessor.prototype.parseSafeCURIEOrCURIEOrURI=function(a,b,c){a=RDFaProcessor.trim(a);return"["==a.charAt(0)&&"]"==a.charAt(a.length-1)?(a=a.substring(1,a.length-1),a=a.trim(a),0==a.length?null:"_:"==a?this.theOne:this.parseCURIE(a,b,c)):this.parseCURIEOrURI(a,b,c)};
RDFaProcessor.prototype.parseCURIE=function(a,b,c){c=a.indexOf(":");if(0<=c){var e=a.substring(0,c);if(""==e)return(b=b[""])?b+a.substring(c+1):null;if("_"==e)return"_:"+a.substring(c+1);if(RDFaProcessor.NCNAME.test(e)&&(b=b[e]))return b+a.substring(c+1)}return null};RDFaProcessor.prototype.parseCURIEOrURI=function(a,b,c){return(b=this.parseCURIE(a,b,c))?b:this.resolveAndNormalize(c,a)};
RDFaProcessor.prototype.parsePredicate=function(a,b,c,e,d,h){return""==a?null:(a=this.parseTermOrCURIEOrAbsURI(a,b,h?null:c,e,d))&&0==a.indexOf("_:")?null:a};RDFaProcessor.prototype.parseTermOrCURIEOrURI=function(a,b,c,e,d){a=RDFaProcessor.trim(a);if((e=this.parseCURIE(a,e,d))||(e=c[a]))return e;e=a.toLowerCase();return(e=c[e])?e:b&&!this.absURIRE.exec(a)?b+a:this.resolveAndNormalize(d,a)};
RDFaProcessor.prototype.parseTermOrCURIEOrAbsURI=function(a,b,c,e,d){a=RDFaProcessor.trim(a);if(e=this.parseCURIE(a,e,d))return e;if(c){if(b&&!this.absURIRE.exec(a))return b+a;if(b=c[a])return b;b=a.toLowerCase();if(b=c[b])return b}return this.absURIRE.exec(a)?this.resolveAndNormalize(d,a):null};RDFaProcessor.prototype.resolveAndNormalize=function(a,b){var c=a.resolve(b),c=this.parseURI(c);c.normalize();return c.spec};
RDFaProcessor.prototype.parsePrefixMappings=function(a,b){for(var c=this.tokenize(a),e=null,d=0;d<c.length;d++)":"==c[d][c[d].length-1]?e=c[d].substring(0,c[d].length-1):e&&(b[e]=this.target.baseURI?this.target.baseURI.resolve(c[d]):c[d],e=null)};RDFaProcessor.prototype.copyMappings=function(a){var b={},c;for(c in a)b[c]=a[c];return b};RDFaProcessor.prototype.ancestorPath=function(a){for(var b="";a&&a.nodeType!=Node.DOCUMENT_NODE;)b="/"+a.localName+b,a=a.parentNode;return b};
RDFaProcessor.prototype.setContext=function(a){"html"==a.localName&&"XHTML+RDFa 1.1"==a.getAttribute("version")?this.setXHTMLContext():"html"==a.localName||"http://www.w3.org/1999/xhtml"==a.namespaceURI?document.doctype?"-//W3C//DTD XHTML+RDFa 1.0//EN"==document.doctype.publicId&&"http://www.w3.org/MarkUp/DTD/xhtml-rdfa-1.dtd"==document.doctype.systemId?(console.log("WARNING: RDF 1.0 is not supported.  Defaulting to HTML5 mode."),this.setHTMLContext()):"-//W3C//DTD XHTML+RDFa 1.1//EN"==document.doctype.publicId&&
"http://www.w3.org/MarkUp/DTD/xhtml-rdfa-2.dtd"==document.doctype.systemId?this.setXHTMLContext():this.setHTMLContext():this.setHTMLContext():this.setXMLContext()};RDFaProcessor.prototype.setInitialContext=function(){this.vocabulary=null;this.langAttributes=[{namespaceURI:"http://www.w3.org/XML/1998/namespace",localName:"lang"}]};RDFaProcessor.prototype.setXMLContext=function(){this.setInitialContext();this.inHTMLMode=this.inXHTMLMode=!1};
RDFaProcessor.prototype.setHTMLContext=function(){this.setInitialContext();this.langAttributes=[{namespaceURI:"http://www.w3.org/XML/1998/namespace",localName:"lang"},{namespaceURI:null,localName:"lang"}];this.inXHTMLMode=!1;this.inHTMLMode=!0};
RDFaProcessor.prototype.setXHTMLContext=function(){this.setInitialContext();this.inXHTMLMode=!0;this.inHTMLMode=!1;this.langAttributes=[{namespaceURI:"http://www.w3.org/XML/1998/namespace",localName:"lang"},{namespaceURI:null,localName:"lang"}];this.target.graph.terms.alternate="http://www.w3.org/1999/xhtml/vocab#alternate";this.target.graph.terms.appendix="http://www.w3.org/1999/xhtml/vocab#appendix";this.target.graph.terms.bookmark="http://www.w3.org/1999/xhtml/vocab#bookmark";this.target.graph.terms.cite=
"http://www.w3.org/1999/xhtml/vocab#cite";this.target.graph.terms.chapter="http://www.w3.org/1999/xhtml/vocab#chapter";this.target.graph.terms.contents="http://www.w3.org/1999/xhtml/vocab#contents";this.target.graph.terms.copyright="http://www.w3.org/1999/xhtml/vocab#copyright";this.target.graph.terms.first="http://www.w3.org/1999/xhtml/vocab#first";this.target.graph.terms.glossary="http://www.w3.org/1999/xhtml/vocab#glossary";this.target.graph.terms.help="http://www.w3.org/1999/xhtml/vocab#help";
this.target.graph.terms.icon="http://www.w3.org/1999/xhtml/vocab#icon";this.target.graph.terms.index="http://www.w3.org/1999/xhtml/vocab#index";this.target.graph.terms.last="http://www.w3.org/1999/xhtml/vocab#last";this.target.graph.terms.license="http://www.w3.org/1999/xhtml/vocab#license";this.target.graph.terms.meta="http://www.w3.org/1999/xhtml/vocab#meta";this.target.graph.terms.next="http://www.w3.org/1999/xhtml/vocab#next";this.target.graph.terms.prev="http://www.w3.org/1999/xhtml/vocab#prev";
this.target.graph.terms.previous="http://www.w3.org/1999/xhtml/vocab#previous";this.target.graph.terms.section="http://www.w3.org/1999/xhtml/vocab#section";this.target.graph.terms.stylesheet="http://www.w3.org/1999/xhtml/vocab#stylesheet";this.target.graph.terms.subsection="http://www.w3.org/1999/xhtml/vocab#subsection";this.target.graph.terms.start="http://www.w3.org/1999/xhtml/vocab#start";this.target.graph.terms.top="http://www.w3.org/1999/xhtml/vocab#top";this.target.graph.terms.up="http://www.w3.org/1999/xhtml/vocab#up";
this.target.graph.terms.p3pv1="http://www.w3.org/1999/xhtml/vocab#p3pv1";this.target.graph.terms.related="http://www.w3.org/1999/xhtml/vocab#related";this.target.graph.terms.role="http://www.w3.org/1999/xhtml/vocab#role";this.target.graph.terms.transformation="http://www.w3.org/1999/xhtml/vocab#transformation"};RDFaProcessor.prototype.init=function(){};RDFaProcessor.prototype.newSubjectOrigin=function(a,b){};RDFaProcessor.prototype.addTriple=function(a,b,c,e){};
RDFaProcessor.dateTimeTypes=[{pattern:/-?P(?:[0-9]+Y)?(?:[0-9]+M)?(?:[0-9]+D)?(?:T(?:[0-9]+H)?(?:[0-9]+M)?(?:[0-9]+(?:\.[0-9]+)?S)?)?/,type:"http://www.w3.org/2001/XMLSchema#duration"},{pattern:/-?(?:[1-9][0-9][0-9][0-9]|0[1-9][0-9][0-9]|00[1-9][0-9]|000[1-9])-[0-9][0-9]-[0-9][0-9]T(?:[0-1][0-9]|2[0-4]):[0-5][0-9]:[0-5][0-9](?:\.[0-9]+)?(?:Z|[+\-][0-9][0-9]:[0-9][0-9])?/,type:"http://www.w3.org/2001/XMLSchema#dateTime"},{pattern:/-?(?:[1-9][0-9][0-9][0-9]|0[1-9][0-9][0-9]|00[1-9][0-9]|000[1-9])-[0-9][0-9]-[0-9][0-9](?:Z|[+\-][0-9][0-9]:[0-9][0-9])?/,
type:"http://www.w3.org/2001/XMLSchema#date"},{pattern:/(?:[0-1][0-9]|2[0-4]):[0-5][0-9]:[0-5][0-9](?:\.[0-9]+)?(?:Z|[+\-][0-9][0-9]:[0-9][0-9])?/,type:"http://www.w3.org/2001/XMLSchema#time"},{pattern:/-?(?:[1-9][0-9][0-9][0-9]|0[1-9][0-9][0-9]|00[1-9][0-9]|000[1-9])-[0-9][0-9]/,type:"http://www.w3.org/2001/XMLSchema#gYearMonth"},{pattern:/-?[1-9][0-9][0-9][0-9]|0[1-9][0-9][0-9]|00[1-9][0-9]|000[1-9]/,type:"http://www.w3.org/2001/XMLSchema#gYear"}];
RDFaProcessor.deriveDateTimeType=function(a){for(var b=0;b<RDFaProcessor.dateTimeTypes.length;b++){var c=RDFaProcessor.dateTimeTypes[b].pattern.exec(a);if(c&&c[0].length==a.length)return RDFaProcessor.dateTimeTypes[b].type}return null};
RDFaProcessor.prototype.process=function(a,b){a.nodeType==Node.DOCUMENT_NODE?(a=a.documentElement,this.setContext(a)):a.parentNode.nodeType==Node.DOCUMENT_NODE&&this.setContext(a);var c=[],e=function(a){var c=a.indexOf("#");0<=c&&(a=a.substring(0,c));b&&b.baseURIMap&&(a=b.baseURIMap(a));return a};for(c.push({current:a,context:this.push(null,e(a.baseURI))});0<c.length;){var d=c.shift();if(d.parent){if(!d.context.parent||d.context.parent.listMapping!=d.listMapping)for(var h in d.listMapping){var l=
d.listMapping[h];if(0==l.length)this.addTriple(d.parent,d.subject,h,{type:RDFaProcessor.objectURI,value:"http://www.w3.org/1999/02/22-rdf-syntax-ns#nil"});else{for(var g=[],f=0;f<l.length;f++)g.push(this.newBlankNode());for(f=0;f<g.length;f++)this.addTriple(d.parent,g[f],"http://www.w3.org/1999/02/22-rdf-syntax-ns#first",l[f]),this.addTriple(d.parent,g[f],"http://www.w3.org/1999/02/22-rdf-syntax-ns#rest",{type:RDFaProcessor.objectURI,value:f+1<g.length?g[f+1]:"http://www.w3.org/1999/02/22-rdf-syntax-ns#nil"});
this.addTriple(d.parent,d.subject,h,{type:RDFaProcessor.objectURI,value:g[0]})}}}else{var g=d.current,d=d.context,A=!1,k=null,p=null,n=null,t=d.prefixes,l=!1,J=[],B=d.listMapping,M=d.parent?!1:!0,I=d.language,D=d.vocabulary,q=this.parseURI(e(g.baseURI));g.item=null;if(f=g.getAttributeNode("vocab"))f=RDFaProcessor.trim(f.value),0<f.length?(D=f,this.addTriple(g,q.spec,"http://www.w3.org/ns/rdfa#usesVocabulary",{type:RDFaProcessor.objectURI,value:D})):D=this.vocabulary;for(f=0;f<g.attributes.length;f++){var v=
g.attributes[f];if("x"==v.nodeName.charAt(0)&&0==v.nodeName.indexOf("xmlns:")){l||(t=this.copyMappings(t),l=!0);var w=v.nodeName.substring(6),v=RDFaProcessor.trim(v.value);t[w]=this.target.baseURI?this.target.baseURI.resolve(v):v}}if(f=g.getAttributeNode("prefix"))l||(t=this.copyMappings(t),l=!0),this.parsePrefixMappings(f.value,t);l=null;for(f=0;!l&&f<this.langAttributes.length;f++)l=g.getAttributeNodeNS(this.langAttributes[f].namespaceURI,this.langAttributes[f].localName);l&&(f=RDFaProcessor.trim(l.value),
I=0<f.length?f:null);var w=g.getAttributeNode("rel"),v=g.getAttributeNode("rev"),x=g.getAttributeNode("typeof"),G=g.getAttributeNode("property"),K=g.getAttributeNode("datatype"),L=this.inHTMLMode?g.getAttributeNode("datetime"):null,H=g.getAttributeNode("content"),y=g.getAttributeNode("about"),E=g.getAttributeNode("src"),C=g.getAttributeNode("resource"),F=g.getAttributeNode("href"),N=g.getAttributeNode("inlist"),m=[];if(w)for(var z=this.tokenize(w.value),f=0;f<z.length;f++)(h=this.parsePredicate(z[f],
D,d.terms,t,q,this.inHTMLMode&&null!=G))&&m.push(h);var r=[];if(v)for(z=this.tokenize(v.value),f=0;f<z.length;f++)(h=this.parsePredicate(z[f],D,d.terms,t,q,this.inHTMLMode&&null!=G))&&r.push(h);!this.inHTMLMode||null==w&&null==v||null==G||(0==m.length&&(w=null),0==r.length&&(v=null));w||v?(y&&(k=this.parseSafeCURIEOrCURIEOrURI(y.value,t,q)),x&&(n=k),k||(g.parentNode.nodeType==Node.DOCUMENT_NODE?k=e(g.baseURI):d.parentObject&&(k=e(g.parentNode.baseURI)==d.parentObject?e(g.baseURI):d.parentObject)),
C&&(p=this.parseSafeCURIEOrCURIEOrURI(C.value,t,q)),p||(F?p=this.resolveAndNormalize(q,encodeURI(F.value)):E?p=this.resolveAndNormalize(q,encodeURI(E.value)):!x||y||this.inXHTMLMode&&("head"==g.localName||"body"==g.localName)||(p=this.newBlankNode())),!x||y||!this.inXHTMLMode||"head"!=g.localName&&"body"!=g.localName?x&&!y&&(n=p):n=k):!G||H||K?(y&&(k=this.parseSafeCURIEOrCURIEOrURI(y.value,t,q)),!k&&C&&(k=this.parseSafeCURIEOrCURIEOrURI(C.value,t,q)),!k&&F&&(k=this.resolveAndNormalize(q,encodeURI(F.value))),
!k&&E&&(k=this.resolveAndNormalize(q,encodeURI(E.value))),k||(g.parentNode.nodeType==Node.DOCUMENT_NODE?k=e(g.baseURI):!this.inXHTMLMode&&!this.inHTMLMode||"head"!=g.localName&&"body"!=g.localName?x?k=this.newBlankNode():d.parentObject&&(k=e(g.parentNode.baseURI)==d.parentObject?e(g.baseURI):d.parentObject,G||(A=!0)):k=e(g.parentNode.baseURI)==d.parentObject?e(g.baseURI):d.parentObject),x&&(n=k)):(y&&(k=this.parseSafeCURIEOrCURIEOrURI(y.value,t,q),x&&(n=k)),k||g.parentNode.nodeType!=Node.DOCUMENT_NODE?
!k&&d.parentObject&&(k=e(g.parentNode.baseURI)==d.parentObject?e(g.baseURI):d.parentObject):(k=e(g.baseURI),x&&(n=k)),x&&!n&&(C&&(n=this.parseSafeCURIEOrCURIEOrURI(C.value,t,q)),!n&&F&&(n=this.resolveAndNormalize(q,encodeURI(F.value))),!n&&E&&(n=this.resolveAndNormalize(q,encodeURI(E.value))),n||!this.inXHTMLMode&&!this.inHTMLMode||"head"!=g.localName&&"body"!=g.localName||(n=k),n||(n=this.newBlankNode()),p=n));k&&(y||C||n)&&(f=k,x&&!y&&!C&&p&&(f=p),this.newSubjectOrigin(g,f));if(n)for(z=this.tokenize(x.value),
f=0;f<z.length;f++)(l=this.parseTermOrCURIEOrAbsURI(z[f],D,d.terms,t,q))&&this.addTriple(g,n,RDFaProcessor.typeURI,{type:RDFaProcessor.objectURI,value:l});k&&k!=d.parentObject&&(B={},M=!0);if(p){if(w&&N)for(f=0;f<m.length;f++)l=B[m[f]],l||(l=[],B[m[f]]=l),l.push({type:RDFaProcessor.objectURI,value:p});else if(w)for(f=0;f<m.length;f++)this.addTriple(g,k,m[f],{type:RDFaProcessor.objectURI,value:p});if(v)for(f=0;f<r.length;f++)this.addTriple(g,p,r[f],{type:RDFaProcessor.objectURI,value:k})}else{k&&!p&&
(w||v)&&(p=this.newBlankNode());if(w&&N)for(f=0;f<m.length;f++)l=B[m[f]],l||(l=[],B[h]=l),J.push({predicate:m[f],list:l});else if(w)for(f=0;f<m.length;f++)J.push({predicate:m[f],forward:!0});if(v)for(f=0;f<r.length;f++)J.push({predicate:r[f],forward:!1})}if(G)for(r=m=null,K?(m=""==K.value?RDFaProcessor.PlainLiteralURI:this.parseTermOrCURIEOrAbsURI(K.value,D,d.terms,t,q),r=L&&!H?L.value:m==RDFaProcessor.XMLLiteralURI||m==RDFaProcessor.HTMLLiteralURI?null:H?H.value:g.textContent):H?(m=RDFaProcessor.PlainLiteralURI,
r=H.value):L?(r=L.value,m=RDFaProcessor.deriveDateTimeType(r),m||(m=RDFaProcessor.PlainLiteralURI)):w||v||(C&&(r=this.parseSafeCURIEOrCURIEOrURI(C.value,t,q)),!r&&F?r=this.resolveAndNormalize(q,encodeURI(F.value)):!r&&E&&(r=this.resolveAndNormalize(q,encodeURI(E.value))),r&&(m=RDFaProcessor.objectURI)),m||(x&&!y?(m=RDFaProcessor.objectURI,r=n):(r=g.textContent,this.inHTMLMode&&"time"==g.localName&&(m=RDFaProcessor.deriveDateTimeType(r)),m||(m=RDFaProcessor.PlainLiteralURI))),z=this.tokenize(G.value),
f=0;f<z.length;f++)if(h=this.parsePredicate(z[f],D,d.terms,t,q))N?(l=B[h],l||(l=[],B[h]=l),l.push(m==RDFaProcessor.XMLLiteralURI||m==RDFaProcessor.HTMLLiteralURI?{type:m,value:g.childNodes}:{type:m?m:RDFaProcessor.PlainLiteralURI,value:r,language:I})):m==RDFaProcessor.XMLLiteralURI||m==RDFaProcessor.HTMLLiteralURI?this.addTriple(g,k,h,{type:m,value:g.childNodes}):this.addTriple(g,k,h,{type:m?m:RDFaProcessor.PlainLiteralURI,value:r,language:I});if(k&&!A)for(f=0;f<d.incomplete.length;f++)d.incomplete[f].list?
d.incomplete[f].list.push({type:RDFaProcessor.objectURI,value:k}):d.incomplete[f].forward?this.addTriple(g,d.subject,d.incomplete[f].predicate,{type:RDFaProcessor.objectURI,value:k}):this.addTriple(g,k,d.incomplete[f].predicate,{type:RDFaProcessor.objectURI,value:d.subject});n=null;q=k;A?(n=this.push(d,d.subject),n.parentObject=e(g.parentNode.baseURI)==d.parentObject?e(g.baseURI):d.parentObject,n.incomplete=d.incomplete,n.language=I,n.prefixes=t):(n=this.push(d,k),n.parentObject=p?p:k?k:d.subject,
n.prefixes=t,n.incomplete=J,p&&(q=p,B={},M=!0),n.listMapping=B,n.language=I);n.vocabulary=D;M&&c.unshift({parent:g,context:d,subject:q,listMapping:B});for(g=g.lastChild;g;g=g.previousSibling)g.nodeType==Node.ELEMENT_NODE&&c.unshift({current:g,context:n})}}this.inHTMLMode&&this.copyProperties();for(f=0;f<this.finishedHandlers.length;f++)this.finishedHandlers[f](a)};RDFaProcessor.prototype.copyProperties=function(){};
RDFaProcessor.prototype.push=function(a,b){return{parent:a,subject:b?b:a?a.subject:null,parentObject:null,incomplete:[],listMapping:a?a.listMapping:{},language:a?a.language:this.language,prefixes:a?a.prefixes:this.target.graph.prefixes,terms:a?a.terms:this.target.graph.terms,vocabulary:a?a.vocabulary:this.vocabulary}};
function RDFaGraph(){var a=this;this.curieParser={trim:function(a){return a.replace(/^\s\s*/,"").replace(/\s\s*$/,"")},parse:function(b,c){b=this.trim(b);"["==b.charAt(0)&&"]"==b.charAt(b.length-1)&&(b=b.substring(1,b.length-1));var e=b.indexOf(":");if(0<=e){var d=b.substring(0,e);if(""==d)return(d=a.prefixes[""])?d+b.substring(e+1):null;if("_"==d)return"_:"+b.substring(e+1);if(DocumentData.NCNAME.test(d)&&(d=a.prefixes[d]))return d+b.substring(e+1)}return c?a.baseURI.resolve(b):b}};this.base=null;
this.toString=function(a){var c=a&&a.shorten?{graph:this,shorten:!0,prefixesUsed:{}}:null;a&&a.blankNodePrefix&&(c.filterBlankNode=function(c){return"_:"+a.blankNodePrefix+c.substring(2)});if(a&&a.numericalBlankNodePrefix){var e=/^[0-9]+$/;c.filterBlankNode=function(c){var d=c.substring(2);return e.test(d)?"_:"+a.numericalBlankNodePrefix+d:c}}s="";for(var d in this.subjects)s+=this.subjects[d].toString(c),s+="\n";d=a&&a.baseURI?"@base <"+baseURI+"> .\n":"";if(c&&c.shorten)for(var h in c.prefixesUsed)d+=
"@prefix "+h+": <"+this.prefixes[h]+"> .\n";return 0==d.length?s:d+"\n"+s};this.blankNodeCounter=0;this.clear=function(){this.subjects={};this.prefixes={};this.terms={};this.blankNodeCounter=0};this.clear();this.prefixes[""]="http://www.w3.org/1999/xhtml/vocab#";this.prefixes.grddl="http://www.w3.org/2003/g/data-view#";this.prefixes.ma="http://www.w3.org/ns/ma-ont#";this.prefixes.owl="http://www.w3.org/2002/07/owl#";this.prefixes.rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#";this.prefixes.rdfa=
"http://www.w3.org/ns/rdfa#";this.prefixes.rdfs="http://www.w3.org/2000/01/rdf-schema#";this.prefixes.rif="http://www.w3.org/2007/rif#";this.prefixes.skos="http://www.w3.org/2004/02/skos/core#";this.prefixes.skosxl="http://www.w3.org/2008/05/skos-xl#";this.prefixes.wdr="http://www.w3.org/2007/05/powder#";this.prefixes["void"]="http://rdfs.org/ns/void#";this.prefixes.wdrs="http://www.w3.org/2007/05/powder-s#";this.prefixes.xhv="http://www.w3.org/1999/xhtml/vocab#";this.prefixes.xml="http://www.w3.org/XML/1998/namespace";
this.prefixes.xsd="http://www.w3.org/2001/XMLSchema#";this.prefixes.sd="http://www.w3.org/ns/sparql-service-description#";this.prefixes.org="http://www.w3.org/ns/org#";this.prefixes.gldp="http://www.w3.org/ns/people#";this.prefixes.cnt="http://www.w3.org/2008/content#";this.prefixes.dcat="http://www.w3.org/ns/dcat#";this.prefixes.earl="http://www.w3.org/ns/earl#";this.prefixes.ht="http://www.w3.org/2006/http#";this.prefixes.ptr="http://www.w3.org/2009/pointers#";this.prefixes.cc="http://creativecommons.org/ns#";
this.prefixes.ctag="http://commontag.org/ns#";this.prefixes.dc="http://purl.org/dc/terms/";this.prefixes.dcterms="http://purl.org/dc/terms/";this.prefixes.foaf="http://xmlns.com/foaf/0.1/";this.prefixes.gr="http://purl.org/goodrelations/v1#";this.prefixes.ical="http://www.w3.org/2002/12/cal/icaltzd#";this.prefixes.og="http://ogp.me/ns#";this.prefixes.rev="http://purl.org/stuff/rev#";this.prefixes.sioc="http://rdfs.org/sioc/ns#";this.prefixes.v="http://rdf.data-vocabulary.org/#";this.prefixes.vcard=
"http://www.w3.org/2006/vcard/ns#";this.prefixes.schema="http://schema.org/";this.terms.describedby="http://www.w3.org/2007/05/powder-s#describedby";this.terms.license="http://www.w3.org/1999/xhtml/vocab#license";this.terms.role="http://www.w3.org/1999/xhtml/vocab#role";Object.defineProperty(this,"tripleCount",{enumerable:!0,configurable:!1,get:function(){var a=0,c;for(c in this.subjects){var e=this.subjects[c],d;for(d in e.predicates)a+=e.predicates[d].objects.length}return a}})}
RDFaGraph.prototype.newBlankNode=function(){this.blankNodeCounter++;return"_:"+this.blankNodeCounter};RDFaGraph.prototype.expand=function(a){return this.curieParser.parse(a,!0)};RDFaGraph.prototype.shorten=function(a,b){for(prefix in this.prefixes){var c=this.prefixes[prefix];if(0==a.indexOf(c))return b&&(b[prefix]=c),prefix+":"+a.substring(c.length)}return null};
RDFaGraph.prototype.add=function(a,b,c,e){if(a&&b&&c){a=this.expand(a);b=this.expand(b);var d=this.subjects[a];d||(d=new RDFaSubject(this,a),this.subjects[a]=d);e&&e.origin&&d.origins.push(e.origin);"http://www.w3.org/1999/02/22-rdf-syntax-ns#type"==b&&d.types.push(c);a=d.predicates[b];a||(a=new RDFaPredicate(b),d.predicates[b]=a);"string"==typeof c?a.objects.push({type:RDFaProcessor.PlainLiteralURI,value:c}):a.objects.push({type:c.type?this.expand(c.type):RDFaProcessor.PlainLiteralURI,value:c.value?
c.value:"",origin:c.origin,language:c.language})}};
RDFaGraph.prototype.addCollection=function(a,b,c,e){if(a&&b&&c){for(var d=0;d<c.length;d++){var h={type:e&&e.type?e.type:"rdf:PlainLiteral"};e&&e.language&&(h.language=e.language);e&&e.datatype&&(h.datatype=e.datatype);"object"==typeof c[d]?(h.value=c[d].value?c[d].value:"",c[d].type&&(h.type=c[d].type),c[d].language&&(h.language=c[d].language),c[d].datatype&&(h.datatype=c[d].datatype)):h.value=c[d];var l=this.newBlankNode();this.add(a,b,{type:"rdf:object",value:l});this.add(l,"rdf:first",h);a=l;
b="http://www.w3.org/1999/02/22-rdf-syntax-ns#rest"}this.add(a,b,{type:"rdf:object",value:"http://www.w3.org/1999/02/22-rdf-syntax-ns#nil"})}};RDFaGraph.prototype.remove=function(a,b){if(a){a=this.expand(a);var c=this.subjects[c];c&&(b?(b=this.expand(b),delete c.predicates[b]):delete this.subjects[a])}else this.subjects={}};function RDFaSubject(a,b){this.graph=a;this.id=this.subject=b;this.predicates={};this.origins=[];this.types=[]}
RDFaSubject.prototype.toString=function(a){var b=null;"_:"==this.subject.substring(0,2)?b=a&&a.filterBlankNode?a.filterBlankNode(this.subject):this.subject:a&&a.shorten?(b=this.graph.shorten(this.subject,a.prefixesUsed))||(b="<"+this.subject+">"):b="<"+this.subject+">";var c=!0,e;for(e in this.predicates)c?c=!1:b+=";\n",b+=" "+this.predicates[e].toString(a);return b+" ."};
RDFaSubject.prototype.toObject=function(){var a={subject:this.subject,predicates:{}},b;for(b in this.predicates){var c=this.predicates[b],e={predicate:b,objects:[]};a.predicates[b]=e;for(var d=0;d<c.objects.length;d++){var h=c.objects[d];if(h.type==RDFaProcessor.XMLLiteralURI){for(var l=new XMLSerializer,g="",f=0;f<h.value.length;f++)h.value[f].nodeType==Node.ELEMENT_NODE?g+=l.serializeToString(h.value[f]):h.value[f].nodeType==Node.TEXT_NODE&&(g+=h.value[f].nodeValue);e.objects.push({type:h.type,
value:g,language:h.language})}else h.type==RDFaProcessor.HTMLLiteralURI?(g=0==h.value.length?"":h.value[0].parentNode.innerHTML,e.objects.push({type:h.type,value:g,language:h.language})):e.objects.push({type:h.type,value:h.value,language:h.language})}}return a};RDFaSubject.prototype.getValues=function(){for(var a=[],b=0;b<arguments.length;b++){var c=this.graph.curieParser.parse(arguments[b],!0);if(c=this.predicates[c])for(var e=0;e<c.objects.length;e++)a.push(c.objects[e].value)}return a};
function RDFaPredicate(a){this.predicate=this.id=a;this.objects=[]}RDFaPredicate.getPrefixMap=function(a){for(var b={};a.attributes;){for(var c=0;c<a.attributes.length;c++)if("http://www.w3.org/2000/xmlns/"==a.attributes[c].namespaceURI){var e=a.attributes[c].localName;"xmlns"==a.attributes[c].localName&&(e="");e in b||(b[e]=a.attributes[c].nodeValue)}a=a.parentNode}return b};
RDFaPredicate.prototype.toString=function(a){var b=null;a&&a.shorten&&a.graph?(b=a.graph.shorten(this.predicate,a.prefixesUsed))||(b="<"+this.predicate+">"):b="<"+this.predicate+">";for(var b=b+" ",c=0;c<this.objects.length;c++)if(0<c&&(b+=", "),"http://www.w3.org/1999/02/22-rdf-syntax-ns#object"==this.objects[c].type)"_:"==this.objects[c].value.substring(0,2)?b=a&&a.filterBlankNode?b+a.filterBlankNode(this.objects[c].value):b+this.objects[c].value:a&&a.shorten&&a.graph?b=(u=a.graph.shorten(this.objects[c].value,
a.prefixesUsed))?b+u:b+("<"+this.objects[c].value+">"):b+="<"+this.objects[c].value+">";else if("http://www.w3.org/2001/XMLSchema#integer"==this.objects[c].type||"http://www.w3.org/2001/XMLSchema#decimal"==this.objects[c].type||"http://www.w3.org/2001/XMLSchema#double"==this.objects[c].type||"http://www.w3.org/2001/XMLSchema#boolean"==this.objects[c].type)b+=this.objects[c].value;else if("http://www.w3.org/1999/02/22-rdf-syntax-ns#XMLLiteral"==this.objects[c].type){for(var e=new XMLSerializer,d="",
h=0;h<this.objects[c].value.length;h++)if(this.objects[c].value[h].nodeType==Node.ELEMENT_NODE){var l=RDFaPredicate.getPrefixMap(this.objects[c].value[h]),g=[],f;for(f in l)g.push(f);g.sort();for(var A=this.objects[c].value[h].cloneNode(!0),k=0;k<g.length;k++)A.setAttributeNS("http://www.w3.org/2000/xmlns/",0==g[k].length?"xmlns":"xmlns:"+g[k],l[g[k]]);d+=e.serializeToString(A)}else this.objects[c].value[h].nodeType==Node.TEXT_NODE&&(d+=this.objects[c].value[h].nodeValue);b+='"""'+d.replace(/"""/g,
'\\"\\"\\"')+'"""^^<http://www.w3.org/1999/02/22-rdf-syntax-ns#XMLLiteral>'}else"http://www.w3.org/1999/02/22-rdf-syntax-ns#HTML"==this.objects[c].type?b=0==this.objects[c].value.length?b+'""""""^^<http://www.w3.org/1999/02/22-rdf-syntax-ns#HTML>':b+('"""'+this.objects[c].value[0].parentNode.innerHTML.replace(/"""/g,'\\"\\"\\"')+'"""^^<http://www.w3.org/1999/02/22-rdf-syntax-ns#HTML>'):(e=this.objects[c].value.toString(),b=0<=e.indexOf("\n")||0<=e.indexOf("\r")?b+('"""'+e.replace(/"""/g,'\\"\\"\\"')+
'"""'):b+('"'+e.replace(/"/g,'\\"')+'"'),"http://www.w3.org/1999/02/22-rdf-syntax-ns#PlainLiteral"!=this.objects[c].type?b+="^^<"+this.objects[c].type+">":this.objects[c].language&&(b+="@"+this.objects[c].language));return b};GraphRDFaProcessor.prototype=new RDFaProcessor;GraphRDFaProcessor.prototype.constructor=RDFaProcessor;function GraphRDFaProcessor(a){RDFaProcessor.call(this,a)}GraphRDFaProcessor.prototype.getObjectSize=function(a){var b=0,c;for(c in a)a.hasOwnProperty(c)&&b++;return b};
GraphRDFaProcessor.prototype.init=function(){var a=this;this.finishedHandlers.push(function(b){for(var c in a.target.graph.subjects)0==a.getObjectSize(a.target.graph.subjects[c].predicates)&&delete a.target.graph.subjects[c]})};GraphRDFaProcessor.prototype.newBlankNode=function(){return this.target.graph.newBlankNode()};
GraphRDFaProcessor.prototype.newSubjectOrigin=function(a,b){for(var c=this.newSubject(null,b),e=0;e<c.origins.length;e++)if(c.origins[e]===a)return;c.origins.push(a);a.data||Object.defineProperty(a,"data",{value:c,writable:!1,configurable:!0,enumerable:!0})};GraphRDFaProcessor.prototype.newSubject=function(a,b){var c=this.target.graph.subjects[b];c||(c=new RDFaSubject(this.target.graph,b),this.target.graph.subjects[b]=c);return c};
GraphRDFaProcessor.prototype.addTriple=function(a,b,c,e){var d=this.newSubject(a,b);b=d.predicates[c];b||(b=new RDFaPredicate(c),d.predicates[c]=b);for(var h=0;h<b.objects.length;h++)if(b.objects[h].type==e.type&&b.objects[h].value==e.value){b.objects[h].origin!==a&&(Array.isArray(b.objects[h].origin)||(c=[],c.push(b.objects[h].origin),b.objects[h].origin=c),b.objects[h].origin.push(a));return}b.objects.push(e);e.origin=a;c==RDFaProcessor.typeURI&&d.types.push(e.value)};
GraphRDFaProcessor.rdfaCopyPredicate="http://www.w3.org/ns/rdfa#copy";GraphRDFaProcessor.rdfaPatternType="http://www.w3.org/ns/rdfa#Pattern";
GraphRDFaProcessor.prototype.copyProperties=function(){var a=[],b={},c;for(c in this.target.graph.subjects){var e=this.target.graph.subjects[c],d=e.predicates[GraphRDFaProcessor.rdfaCopyPredicate];if(d){a.push(c);for(var h=0;h<d.objects.length;h++)if(d.objects[h].type==RDFaProcessor.objectURI){var l=d.objects[h].value,g=this.target.graph.subjects[l];if(g){var f=g.predicates[RDFaProcessor.typeURI];if(f){for(var A=!1,k=0;k<f.objects.length&&!A;k++)f.objects[k].value==GraphRDFaProcessor.rdfaPatternType&&
f.objects[k].type==RDFaProcessor.objectURI&&(A=!0);if(A){b[l]=!0;for(var p in g.predicates)if(l=g.predicates[p],p==RDFaProcessor.typeURI){if(1!=l.objects.length)for(k=0;k<l.objects.length;k++)l.objects[k].value!=GraphRDFaProcessor.rdfaPatternType&&(f=e.predicates[p],f||(f=new RDFaPredicate(p),e.predicates[p]=f),f.objects.push({type:l.objects[k].type,value:l.objects[k].value,language:l.objects[k].language,origin:l.objects[k].origin}),e.types.push(l.objects[k].value))}else for(f=e.predicates[p],f||
(f=new RDFaPredicate(p),e.predicates[p]=f),k=0;k<l.objects.length;k++)f.objects.push({type:l.objects[k].type,value:l.objects[k].value,language:l.objects[k].language,origin:l.objects[k].origin})}}}}}}for(h=0;h<a.length;h++)e=this.target.graph.subjects[a[h]],delete e.predicates[GraphRDFaProcessor.rdfaCopyPredicate];for(c in b)delete this.target.graph.subjects[c]};
